# Generated by Django 4.2.2 on 2023-07-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fear_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feartracker',
            name='date',
            field=models.DateField(),
        ),
    ]
