# Generated by Django 4.2.2 on 2023-07-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fear_tracker', '0002_alter_feartracker_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feartracker',
            name='activity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='feartracker',
            name='disturbing_thoughts',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='feartracker',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
