# Generated by Django 4.2.2 on 2023-07-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fear_tracker', '0003_alter_feartracker_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feartracker',
            name='time',
            field=models.TimeField(),
        ),
    ]
