# Generated by Django 4.2.2 on 2023-07-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
