# Generated by Django 4.2.2 on 2023-07-17 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psycho_tests', '0006_alter_answer_psycho_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AddField(
            model_name='psychotest',
            name='answers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psycho_tests.answers'),
        ),
    ]
