# Generated by Django 4.2.2 on 2023-07-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psycho_tests', '0003_testresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalityTest',
        ),
    ]
