# Generated by Django 4.2.2 on 2023-07-10 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psycho_tests', '0004_delete_personalitytest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50)),
                ('psycho_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psycho_tests.psychotest')),
            ],
        ),
    ]
