# Generated by Django 4.2.2 on 2023-07-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psycho_tests', '0007_answers_delete_answer_psychotest_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychotest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('published', 'Published')], default='pending', max_length=15),
        ),
    ]
